CREATE TABLE `client_mse` (
  `client_mse_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `client_id` int(10) unsigned NOT NULL,
  `appearance` varchar(45) DEFAULT NULL,
  `other_appearance` varchar(45) DEFAULT NULL,
  `speech` varchar(45) DEFAULT NULL,
  `other_speech` varchar(45) DEFAULT NULL,
  `eye_contact` varchar(45) DEFAULT NULL,
  `other_eyecontact` varchar(45) DEFAULT NULL,
  `motor_activity` varchar(45) DEFAULT NULL,
  `other_motoractivity` varchar(45) DEFAULT NULL,
  `affect` varchar(45) DEFAULT NULL,
  `other_affect` varchar(45) DEFAULT NULL,
  `mood` varchar(45) DEFAULT NULL,
  `other_mood` varchar(45) DEFAULT NULL,
  `orientation_impairment` varchar(45) DEFAULT NULL,
  `memory_impairment` varchar(45) DEFAULT NULL,
  `other_memory_impairment` varchar(45) DEFAULT NULL,
  `attention` varchar(45) DEFAULT NULL,
  `cognition_comments` varchar(45) DEFAULT NULL,
  `hallucinations` varchar(45) DEFAULT NULL,
  `other_perceptions` varchar(45) DEFAULT NULL,
  `perceptions_comments` varchar(45) DEFAULT NULL,
  `suicidality` varchar(45) DEFAULT NULL,
  `homicidality` varchar(45) DEFAULT NULL,
  `delusions` varchar(45) DEFAULT NULL,
  `other_delusions` varchar(45) DEFAULT NULL,
  `thoughts_comments` varchar(45) DEFAULT NULL,
  `behavior` varchar(45) DEFAULT NULL,
  `other_behavior` varchar(45) DEFAULT NULL,
  `behavior_comments` varchar(45) DEFAULT NULL,
  `insight` varchar(45) DEFAULT NULL,
  `other_insight` varchar(45) DEFAULT NULL,
  `judgement` varchar(45) DEFAULT NULL,
  `judgement_other` varchar(45) DEFAULT NULL,
  `created_on` datetime DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  PRIMARY KEY (`client_mse_id`),
  UNIQUE KEY `client_id_UNIQUE` (`client_id`),
  KEY `fk_client_mse_client_id_idx` (`client_id`),
  CONSTRAINT `fk_client_mse_client_id` FOREIGN KEY (`client_id`) REFERENCES `client` (`client_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;
