CREATE TABLE `treatment_data` (
  `treatment_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `session_id` int(10) unsigned NOT NULL,
  `client_id` int(10) unsigned NOT NULL,
  `physical_comp` varchar(200) DEFAULT NULL,
  `mental_comp` varchar(200) DEFAULT NULL,
  `onset_date` date DEFAULT NULL,
  `duration` varchar(45) DEFAULT NULL,
  `degree` int(11) DEFAULT NULL,
  `therapy_applied` varchar(100) DEFAULT NULL,
  `casehistory` varchar(450) DEFAULT NULL,
  `psy_evaluation` varchar(250) DEFAULT NULL,
  `lab_testing` varchar(200) DEFAULT NULL,
  `diagnosis` varchar(200) DEFAULT NULL,
  `diff_diagnosis` varchar(200) DEFAULT NULL,
  `formulation` varchar(200) DEFAULT NULL,
  `client_doc_link` varchar(500) DEFAULT NULL,
  `created_on` datetime DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  PRIMARY KEY (`treatment_id`),
  UNIQUE KEY `session_id_UNIQUE` (`session_id`),
  KEY `fk_treatment_data_session_id_idx` (`session_id`),
  KEY `fk_treatment_data_client_id_idx` (`client_id`),
  CONSTRAINT `fk_treatment_data_client_id` FOREIGN KEY (`client_id`) REFERENCES `client` (`client_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_treatment_data_session_id` FOREIGN KEY (`session_id`) REFERENCES `session` (`session_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;
